adding exception message
Krechin94/FirstGame pull request #1
Opened 2023-02-25 12:33 UTC by Krechin94

2023-02-26 15:44 UTC, axtox requested changes
Код протестировал - новая фича с экспешенами работает, но нужно неболшие доработки

2023-02-26 15:44 UTC, axtox commented on PizdilovoGame.sln
> -VisualStudioVersion = 17.1.32210.238
Версия понизилась, возможно ты открыл проект в старом Visual Studio. 

Попробуй открыть проект в новом Visual Studio 2022, запусти программу, сохрани все и посмотри изменится ли файл проекта. Если да то запуш его, потому что мы так и будем из пулереквеста в пулреквест видеть эти изменения, лучше работать в одной версии

2023-02-26 15:44 UTC, axtox commented on PizdilovoGame/Baffi.cs
> +        /*internal void Buffs(Player player, IPlayer enemy)
Закоментированный код пушть не стоит: если нужно обратится в историю - то всегда можно открыть историю коммитов и достать нужный код, а если он не нужен - удали его полностью, чтобы не забивать шумом кодовую базу

2023-02-26 15:44 UTC, axtox commented on PizdilovoGame/MyException.cs
> +    internal class MyException:Exception
Название этого класса не отражает сути - это ошибка, судя по описанию, является ошибкой ввода, можно например назвать класс "IncorrectUserInputException" или "WrongNumberProvidedException" или "OutsideOfScopeInputException" - тут можно пофантазировать, главное чтобы название отражало суть ошибки в двух словах

2023-02-26 15:44 UTC, axtox commented on PizdilovoGame/MyException.cs
> +    internal class MyException:Exception
Класс должен быть public так как если вне проекта кто-то захочет поймать это исключение через try/catch он не сможет этого сделать, поскольку класс не будет виден вне этого проекта

2023-02-26 15:44 UTC, axtox commented on PizdilovoGame/MyException.cs
> +        public MyException() : base("Пожалуйста введи число от 1 до 3Не надо вводить буквы" )
После цифры 3 в строке текста об ошибке нужно поставить или точку или пробел или новую строку `\n` 

btw очень здорово что сообщение создается прям сразу с классом, если не планируется других сообщений

2023-02-26 15:44 UTC, axtox commented on PizdilovoGame/Player.cs
> +                    /*int buff = random.Next(0, 4);
Законментированный код нужно убрать

2023-02-26 15:44 UTC, axtox commented on PizdilovoGame/Player.cs
> +                int kuda= -1;
Форматирование кода - нужно соблюдать отсутпы, чтобы весь код был в одной иерархии. То есть после каждой открытой фигуроной скобки  `{` нужно начинать новый код с отступа (один `tab` или 4 пробела). После каждой закрытой скобки `}` новый код с новой строчки пишется опять на 4 пробела назад:

```csharp
public void SomeMethod() 
{
    var newCodeHere = new NewClass(); // новый код уже с отступом
    if (newCodeHere.IsCorrect)
    {
        newCodeHere.DoSomething(); // еще отсутп, так как начался новый блок кода
    }
    newCodeHere.DoSomethingElse(); // возвращаем отступ, так как блок вверху закончился
}
```

2023-02-26 15:44 UTC, axtox commented on PizdilovoGame/Program.cs
> +
По гайдам после метода сразу должен идти открывающий символ `{`, здесь лишняя пустая строчка, нужно убрать

2023-02-26 15:44 UTC, axtox commented on PizdilovoGame/Program.cs
> +
Здесь пробел очень к месту, так как визуально отделяет метод от поля `random` 👍

2023-02-26 15:44 UTC, axtox commented on PizdilovoGame/Program.cs
>          {
Я проверил как работает приложение - все таки грустно что эксепшн с ссобщением мы выбрасываем, а в консоль она не пишется, приложение просто вылетает. 

Давай сделаем чтобы все тело метода `main` было обернуто в try/catch котрый ловит ВСЕ ошибки, пишет в консоль сообщение текста ошикби и выходит из программы 

```csharp
static void Main(string[] args)
{
    try
    {
        ...code goes here...
    }
    catch (Exception e) // ловим глобальные ошибки (но не абсолютно все, это позже будет объясняться)
    {
        Console.WriteLine(e.message); // пишем в консоль ошибку
        return; // убиваем программу
    }
}

2023-02-26 15:44 UTC, axtox commented on PizdilovoGame/VvodChisla.cs
> +        public int chislo;
Публичные свойства и поля с большой буквы

2023-02-26 15:44 UTC, axtox commented on PizdilovoGame/VvodChisla.cs
> +         chislo = int.Parse(Console.ReadLine());
int.Parse() может упасть с ошибкой, если передать ему буквы. Получается упадет стандартное сообщение, и оно мало что даст пользователю когда он ее увидит потому что она хз где упала.

ЛУчше всего обернуть вызов int.Parse в блок try/catch, ловить ошибки которые он может бросить, и бросать `MyException` в catch с нормальным сообщением

```csharp
try
{
    chislo = int.Parse(Console.ReadLine());
}
catch (FormatException fe)
{
    throw MyException();
}
...more catches...
```

2023-02-26 15:44 UTC, axtox commented on PizdilovoGame/VvodChisla.cs
> +using System.Collections.Generic;
Серым отмечены неиспользуемые библиотеки и пространства имен - нужно их почистить оставить только используемые

2023-02-27 23:43 UTC, axtox requested changes

2023-02-27 23:43 UTC, axtox commented on PizdilovoGame/Player.cs
> -        {
Добавился лишний пробел и по файлу много неправильных отступов (строка 35-36, 66-67)

2023-03-02 18:27 UTC, Krechin94 commented on PizdilovoGame.sln
> -VisualStudioVersion = 17.1.32210.238
Исправил, все работает commit [Work on mistakes](https://github.com/Krechin94/FirstGame/pull/1/commits/f96625a3521f1bd818dfc657432e20241ca9c14f)

2023-03-02 18:28 UTC, Krechin94 commented on PizdilovoGame/Baffi.cs
> +        /*internal void Buffs(Player player, IPlayer enemy)
Все комментарии удалены commit [Work on mistakes](https://github.com/Krechin94/FirstGame/pull/1/commits/f96625a3521f1bd818dfc657432e20241ca9c14f)

2023-03-02 18:29 UTC, Krechin94 commented on PizdilovoGame/MyException.cs
> +    internal class MyException:Exception
Название exception исправил на WrongUserInputException commit [Work on mistakes](https://github.com/Krechin94/FirstGame/pull/1/commits/f96625a3521f1bd818dfc657432e20241ca9c14f)

2023-03-02 18:29 UTC, Krechin94 commented on PizdilovoGame/MyException.cs
> +    internal class MyException:Exception
исправил на public commit [Work on mistakes](https://github.com/Krechin94/FirstGame/pull/1/commits/f96625a3521f1bd818dfc657432e20241ca9c14f)

2023-03-02 18:30 UTC, Krechin94 commented on PizdilovoGame/MyException.cs
> +        public MyException() : base("Пожалуйста введи число от 1 до 3Не надо вводить буквы" )
Исправил, все работает, commit [Work on mistakes](https://github.com/Krechin94/FirstGame/pull/1/commits/f96625a3521f1bd818dfc657432e20241ca9c14f)

2023-03-02 18:32 UTC, Krechin94 commented on PizdilovoGame/Program.cs
>          {
Исправил, Теперь сообщение выводится в консоль, а также записывается в файл
 commit [Work on mistakes](https://github.com/Krechin94/FirstGame/pull/1/commits/f96625a3521f1bd818dfc657432e20241ca9c14f)
[Loggin programm mistakes in file](https://github.com/Krechin94/FirstGame/pull/1/commits/7e3b9a6c12e3e9613836946a1d1da927ed9421dc)

2023-03-02 18:32 UTC, Krechin94 commented on PizdilovoGame/VvodChisla.cs
> +        public int chislo;
Исправил, commit [Work on mistakes](https://github.com/Krechin94/FirstGame/pull/1/commits/f96625a3521f1bd818dfc657432e20241ca9c14f)

2023-03-02 18:34 UTC, Krechin94 commented on PizdilovoGame/VvodChisla.cs
> +         chislo = int.Parse(Console.ReadLine());
Не исправил, есть вопросы по этому пункту

2023-03-02 18:34 UTC, Krechin94 commented on PizdilovoGame/VvodChisla.cs
> +using System.Collections.Generic;
Все почистил, commit [Work on mistakes](https://github.com/Krechin94/FirstGame/pull/1/commits/f96625a3521f1bd818dfc657432e20241ca9c14f)

2023-03-02 18:38 UTC, Krechin94 commented on PizdilovoGame/Player.cs
> -        {
Если я все правильно понял, то исправил тут [Some changes on Axtox comment](https://github.com/Krechin94/FirstGame/pull/1/commits/e0e29add3fcb08f2e18a996e56b02a1d4affcd37)

2023-03-03 04:06 UTC, axtox requested changes

2023-03-03 04:06 UTC, axtox commented on PizdilovoGame/Program.cs
> +                using (var sw = new StreamWriter("C:\\Users\\79111\\Desktop\\Git\\Log.txt"))
Из-за того что путь абсолютный и ведет в определенное место на твоем копьютере, это не будет работать не других копмьютерах. Вот что я получил при запуске и вводе неправильного числа

![image](https://user-images.githubusercontent.com/11292461/222609787-dc6b506a-2492-455e-a50f-2e53bf4f233d.png)


Чтобы это исправить, воспользуйся специальной директивой AppData - это папка специально создана ребятами из Windows и есть у всех виндоуз пользователей. Она обычно находится в папке пользователя и скрыта - все приложения хранят там свои данные, а мы будем хранить там логи по ошибкам.
Чтобы получить путь к этой папке на конкретном копьютере достаточно обратится к методу `Environment.GetFolderPath()` - этот метод принимает на вход перечисление `Environment.SpecialFolder` - можешь найти его в интернете - это просто список всех возможных системных папок. Нам нужен `Environment.SpecialFolder.ApplicationData` поэтому вызов будет такой:

```csharp
string pathToAppData = Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData)
```

и таким образом в переменную `pathToAppData` запишется путь к папке AppData на данном копьютере.

Более того, на новом копьютере не будет файла Log.txt и надо указать явно StreamWriter что надо создать такой файл, если он не существует! Почитай документацию StreamWriter, у него есть такой конструктор, который позволит создать файл, если его нет по этому пути

2023-03-03 04:06 UTC, axtox commented on PizdilovoGame/Program.cs
> +                        throw new NullInputException();
Идея интересная, но по всей видимости ты пытаешься обыграть ситуацию, когда введено непраивльное число (например буква вместо числа) и в этой ситуации в Number будет 0, потому что инициализация числа НЕ была произведена. 
На самом же деле ты просто дублируешь логику, которая уже итак прописана в классе `VvodChisla` - ты итак ловишь там ошибку и у тебя уже есть описанное сообщение ошибки и даже сама ошибка уже создана - это `WrongUserInputException`, иными словами получается что ты этим кодом говоришь что дальнейшая работа приложения невозможна, поэтому можно сразу там и выбросить ошибку внутри VvodChisla, то есть:

```csharp
try
{
    Chislo = int.Parse(Console.ReadLine());
    if (Chislo != 1 && Chislo != 2 && Chislo != 3)
    {
        throw new WrongUserInputException();
    }
}
catch (FormatException ex)
{
        // пробросить экспешн в новым сообщением, таким образом 
        // мы говорим что мы знаем что делаем, просто хотим другое 
        // сообщение об ошибке сделать
        throw new WrongUserInputException(); 
}
```

Как видишь код сверху не пройдет дальше, а прекратится немедленно, а наверх в Program.cs ты поймаешь его и выведешь на экран корректное сообщение, при этом программа дальше выполняться не будет и тебе не нужно делать дополнительные проверки здесь, ты можешь быть уверен что твой VvodChisla (почти) никогда не даст программе выполняться дальше, если был введен неправильный выбор (будь то неправильное число или буква)

2023-03-03 04:06 UTC, axtox commented on PizdilovoGame/MyException.cs
> +    internal class MyException:Exception
Здесь все супер теперь, но вот файл все еще называется по-старому: `MyException.cs`, его тоже надо переименовать и давай  переместим его в новую папку `Exceptions`, однако когда будешь перемещать этот файл в новую папку в проекте, нужно будет переименовать и его namespace - потому что неймспейс по гайдам дожлен совпадать с путём к файлу, где `PizdelovoGame` - это типа корень пути, то есть у тебя будет

```csharp
namespace PizdelovoGame.Exceptions
{
...
}
```

и теперь все новые ошибки которые ты будешь создавать будут лежать в этой папке, а заново созданные файлы в этой папке сразу будут иметь правильный namespace

2023-03-03 04:06 UTC, axtox commented on PizdilovoGame/Program.cs
>          {
Супер, может еще напишем в консоль перед смертью что-то типа:
```csharp
$"Произошло что-то непредвиденное и программа дальше работать не будет. Смотрите логи в папке {Environment.SpecialFolder.ApplicationData}"
```

Таким образом те кто выполнляет твою программу в консоли увидят сообщение прежде чем программа закроется. 

В примере выше я использовал конструкцию Interpolated String `$` - [вот ссылка](https://stackoverflow.com/questions/31014869/what-does-mean-before-a-string), лучше использовать всегда эту конструкцию вместо конкатенации строк (строка + строка)

2023-03-03 04:06 UTC, axtox commented on PizdilovoGame/Player.cs
> -        {
Обязательно возьми последнюю версию (нажми Pull в Git) и просмотри мои изменения, чтобы наглядно понимать о чем речь - со временем ты придешь к этому, главное насмотренность

Ссылка на коммит
f96625a3521f1bd818dfc657432e20241ca9c14f

2023-03-03 04:21 UTC, axtox commented on PizdilovoGame/Program.cs
> +                        throw new NullInputException();
Для лучшего понимания зачем нужен проброс - это делается для того, чтобы другим программистам в будущем было бы проще найти конкретное место и причину ошибки.

Вот представь, что ты увидел в консоли ошибку `NullReferenceException` - это самый распространенный тип ошибки. Ты даже нашел где она произошла, но все ещё не понимаешь как так вышло.

А с таким подходом, ты дашь понять что твои намерения определены, и что ты намеренно запрещаешь программе выполняться дальше, мало того пишешь корректное сообщение об ошибке, чтобы и пользователь и другой программист могли локализовать и решить проблему.

В данном примере мы ловим `FormatException`, и никак не используем его, и выбрасываем вместо него совершенно другой `Exception`, который отражает реальное положение дел (причину ошибки)

Но если угодно, мы можем сохранить информацию о первой ошибке, передав ее в конструктор `WrongInputException` - в базовом классе `Exception` уже есть такой конструктор, чтобы им воспользоваться тебе надо создать ещё один контруктор, который будет принимать другую ошибку в качестве параметра:

```csharp
public WrongInputException (Exception ex) : base ("Ты неправильно ввел данные дурила", ex) { }
```

Код выше создаёт экземпляр твоего класса ошибки, пользуюсь стандартным конструктором (`base`) который имеется в базовом классе `Exception` - он буквально делает 2 вещи - сохраняет твое сообщение в поле `Message` и сохраняет ссылку на первую ошибку в поле `InnerException`

Таким образом и сообщение крутое будет, и информация о настоящей ошибке, вызвавшей все это, будет тоже сохранена

2023-03-03 11:38 UTC, Krechin94 commented on PizdilovoGame/Program.cs
>          {
мы всегда и использовали эту конструкцию

2023-03-05 12:38 UTC, Krechin94 commented on PizdilovoGame/MyException.cs
> +    internal class MyException:Exception
Все исправлено в [Adding new folders with gamelogic and exceptions](https://github.com/Krechin94/FirstGame/pull/1/commits/47f88c03c346436aa458e85c08deae08fe81a41d)

2023-03-05 12:45 UTC, Krechin94 commented on PizdilovoGame/Program.cs
>          {
Сделано [adding message when we catch a mistake](https://github.com/Krechin94/FirstGame/pull/1/commits/958e72686006efa383529a56f8b1f31bea537fd8)

2023-03-05 12:46 UTC, Krechin94 commented on PizdilovoGame/VvodChisla.cs
> +         chislo = int.Parse(Console.ReadLine());
исправлено

2023-03-05 12:46 UTC, Krechin94 commented on PizdilovoGame/Player.cs
> -        {
последняя версия добавлена

2023-03-05 12:47 UTC, Krechin94 commented on PizdilovoGame/Program.cs
> +                using (var sw = new StreamWriter("C:\\Users\\79111\\Desktop\\Git\\Log.txt"))
все сделано, вот конечный результат [Cheking and creating path for loggin mistakes and creating new class …](https://github.com/Krechin94/FirstGame/pull/1/commits/9cbb3c00bd72b437cdc6f3182cf23cb55a6f7df0)

2023-03-05 12:50 UTC, Krechin94 commented on PizdilovoGame/Program.cs
> +                        throw new NullInputException();
все исправлено

2023-03-05 14:38 UTC, axtox approved these changes

2023-03-08 19:42 UTC, merged