Events lambda delegates and writing player info into console
Krechin94/FirstGame pull request #2
Opened 2023-03-11 21:49 UTC by Krechin94

In this branch we made goodloking and informative input in console, where we can watch Hp, Mana and Names of player ONLINE. Online input in console made with the help of EVENTS

2023-03-12 01:44 UTC, axtox requested changes

2023-03-12 01:44 UTC, axtox commented on PizdilovoGame/GameLogic/WritingInfoInConsole.cs
> +        string[] arrayProbel = new string[10] { "", " ", "  ", "   ", "    ","     ","      ", "       ", "        ", "         " };
Лучше всего заменить на добавление литерала `\t`, который самостоятельно добавляет пробелы чтобы строка равнялась 4 символам, а рассчитать сколько нужно добавить `\t` просто получив остаток от деления на `% 4` числа `longest` - остаток и есть количество нужных `\t`

2023-03-12 01:44 UTC, axtox commented on PizdilovoGame/GameLogic/WritingInfoInConsole.cs
> +            var playerName2 = $"{player2.Name}";
Одинаковые строчки кода означают что это действие может совершаться в методе

2023-03-12 01:44 UTC, axtox commented on PizdilovoGame/GameLogic/WritingInfoInConsole.cs
> +            if (playerName1.Length > playerHp1.Length)
Можно добавить все три `Length` в массив или коллецию и отсортировать по возрастанию, и тогда первый элемент массива и будет longest.
```csharp
var displayInfoLengths = new List<string> 
{
    playerName1.Length,
    playerName2.Length,
    playerHp1.Length,
    playerHp2.Length,
    playerMana1.Length,
    playerMana2.Length,
}
displayInfoLengths.Sort();
```

2023-03-12 01:44 UTC, axtox commented on PizdilovoGame/GameLogic/WritingInfoInConsole.cs
> +                    raznitsaName = 0;
Теперь когда извествен longest не обязательно рассчитывать разницы, достаточно опередлить сколько раз надо добавить `\t` в каждом случае

2023-03-12 01:44 UTC, axtox commented on PizdilovoGame/Player.cs
> +        }
не хватает пустой строки между свойствами

2023-03-12 01:44 UTC, axtox commented on PizdilovoGame/Player.cs
> +        }
здесь тоже нужна пустая строка чтобы отделить её визуально от автободи свойств

2023-03-12 01:44 UTC, axtox commented on PizdilovoGame/Player.cs
> -        public override string ToString()
Предлагаю оставить `override ToString()` для тех кто захочет попробовать распечатать (первратить в текст) целого инрока, но чтобы он выводил просто имя игрока `Name`;

2023-03-15 15:30 UTC, Krechin94 commented on PizdilovoGame/GameLogic/WritingInfoInConsole.cs
> +        string[] arrayProbel = new string[10] { "", " ", "  ", "   ", "    ","     ","      ", "       ", "        ", "         " };
Не было задания на логику, поэтому не вижу чем моя логика хуже твоей

2023-03-15 16:21 UTC, Krechin94 commented on PizdilovoGame/GameLogic/WritingInfoInConsole.cs
> +            if (playerName1.Length > playerHp1.Length)
Переделано в [более правильный и читабельный код в логике вывода в консоль](https://github.com/Krechin94/FirstGame/pull/2/commits/ffaa4711952a55ec41e7fef98ee38e72ecf55edb)

2023-03-15 16:21 UTC, Krechin94 commented on PizdilovoGame/GameLogic/WritingInfoInConsole.cs
> +                    raznitsaName = 0;
Сделано по моей логике

2023-03-15 16:22 UTC, Krechin94 commented on PizdilovoGame/Player.cs
> +        }
исправил [добавление пустых строк для разделения](https://github.com/Krechin94/FirstGame/pull/2/commits/cb1bc4d74b7c89f499345f0e09f24a0563b6fbf5)

2023-03-15 16:22 UTC, Krechin94 commented on PizdilovoGame/Player.cs
> +        }
исправил [добавление пустых строк для разделения](https://github.com/Krechin94/FirstGame/pull/2/commits/cb1bc4d74b7c89f499345f0e09f24a0563b6fbf5)

2023-03-15 16:22 UTC, Krechin94 commented on PizdilovoGame/Player.cs
> -        public override string ToString()
добавил [добавление метода ToString](https://github.com/Krechin94/FirstGame/pull/2/commits/24cf1e65a56793fcb8faaefb7a7ff7b123615c4f)

2023-03-15 19:10 UTC, axtox approved these changes

2023-03-15 19:10 UTC, axtox commented on PizdilovoGame/GameLogic/WritingInfoInConsole.cs
> +            var playerName2 = $"{player2.Name}";
не будет исправлено

2023-03-15 19:10 UTC, axtox commented on PizdilovoGame/Player.cs
> +        }
Дополнил в [Исправил ошибки форматирования](https://github.com/Krechin94/FirstGame/pull/2/commits/7d702300995e3caaeb91227341f7e5e793c58078)

2023-03-15 19:10 UTC, axtox commented on PizdilovoGame/Player.cs
> +        }
Исправлено 7d702300995e3caaeb91227341f7e5e793c58078

2023-03-15 19:10 UTC, axtox commented on PizdilovoGame/Player.cs
> -        public override string ToString()
исправили 7d702300995e3caaeb91227341f7e5e793c58078

2023-03-15 19:10 UTC, axtox commented on PizdilovoGame/GameLogic/WritingInfoInConsole.cs
> +        string[] arrayProbel = new string[10] { "", " ", "  ", "   ", "    ","     ","      ", "       ", "        ", "         " };
Согласен, оставляем пробелы, но исправили на динамичекое добавление 7d702300995e3caaeb91227341f7e5e793c58078

2023-03-15 19:10 UTC, axtox commented on PizdilovoGame/GameLogic/WritingInfoInConsole.cs
> +            if (playerName1.Length > playerHp1.Length)
Дополнено в 7d702300995e3caaeb91227341f7e5e793c58078

2023-03-15 19:10 UTC, axtox commented on PizdilovoGame/GameLogic/WritingInfoInConsole.cs
> +                    raznitsaName = 0;
Исправили на динамическое добваление пробелов 7d702300995e3caaeb91227341f7e5e793c58078

2023-03-15 19:11 UTC, merged