Создание нового класса работы с консолью
Krechin94/FirstGame pull request #5
Opened 2023-03-27 13:59 UTC by Krechin94

2023-04-23 14:22 UTC, axtox requested changes

2023-04-23 14:22 UTC, axtox commented on PizdilovoGame/GameLogic/WorkWithFileLogic.cs
> +                sw.WriteLine("Упс Ошибочка");
😁

2023-04-23 14:22 UTC, axtox commented on PizdilovoGame/GameLogic/WritingInConsole.cs
> +    internal static class WritingInConsole
Следует переименовать класс во что-то более абстрактное, ведь смысл здесь именно в том чтобы выводить данные куда-то пользователю, совершенно не обязательно это будет консоль в дальнейшем

Возможно имеет смысл создать интерфейс который будет называться абстрактно, что-то вроде `Messaging`, а метод например `ShowMessage` или как-то так, а уже конкретная реализация, которая пишет в консоль будет `ConsoleMessaging` 

А то сейчас получается вызов выглядит так: 
`WritingInConsole.WriteInConsole`

2023-04-23 14:22 UTC, axtox commented on PizdilovoGame/GameLogic/WritingInConsole.cs
> +        public static void WriteInConsole(string message )
Можно создать еще парочку методов которые будут писать заведомо заданные сообщения системные, в таком случае если у тебя они в нескольких местах в коде встречаются, тебе не придется править текст в них в тысячах мест. 

То есть например, можно сделать метод который выводит ознакомительный текст - `ShowHelp` или `PrintHelp` который бы показывал информацию о том как играть в начале игры, а в последствии можно было бы нажать какую-то кнопку чтобы увидеть этот текст

Также можно сделать например вывод сообщения "вы нанесли урон" и передавать цифру с количеством урона:
`ShowDamageDeal(4)` и можно даже исхитриться и сделать  5 различных вариаций выводимого сообщения типа "ты нанес {damage} урона" или "в этот раз ударил на {damage} урона"

Отличный пример подобного есть в моём проекте [gastro-pimp](https://github.com/axtox/gastro-pimp/blob/master/Bot/Messaging/MessagingBroker.cs)

В последствии мы вообще тексты вынесем в локаль файл, чтобы можно было добавить перевод на другой язык

2023-04-23 14:22 UTC, axtox commented on PizdilovoGame/Player.cs
> +                Console.SetCursorPosition(0, 1);
Такие вещи как выравнивание курсора на определенное место тоже должен видеть только класс по выводу сообщений - это его задача, знать как располагать текст который нужно напечатать

2023-04-23 14:22 UTC, axtox commented on PizdilovoGame/Player.cs
> +            Console.Clear();
Чистка экрана думаю тоже должна перекочевать к класс по управлению выводом текста

2023-10-09 15:45 UTC, Krechin94 commented on PizdilovoGame/GameLogic/WritingInConsole.cs
> +    internal static class WritingInConsole
изменено на ConsoleMessaging

2023-10-09 15:50 UTC, Krechin94 commented on PizdilovoGame/Player.cs
> +                Console.SetCursorPosition(0, 1);
теперь все исправлено[Все выравнивания курсора теперь находятся в методах работы с консолью](https://github.com/Krechin94/FirstGame/commit/1efda54b27902202f379a3036654fbb2609256f5)

2023-10-09 16:10 UTC, Krechin94 commented on PizdilovoGame/Player.cs
> +            Console.Clear();
[теперь точно вся работа с консолью в другом классе](https://github.com/Krechin94/FirstGame/commit/d19e33bf544ced1aa04206c5a61c2a24ecae26e2)

2023-10-09 16:26 UTC, Krechin94 commented on PizdilovoGame/GameLogic/WritingInConsole.cs
> +        public static void WriteInConsole(string message )
все добавлено [добавление нового метода по отображению нанесенного урона, теперь нес…](https://github.com/Krechin94/FirstGame/commit/132dd76168422de9071d73ca38d07ce9b77a8f69)

2023-10-13 12:04 UTC, axtox requested changes

2023-10-13 12:04 UTC, axtox commented on PizdilovoGame/Buffs/HpRestoring.cs
> +        public string Description { get; } = "Заклинание по восстановлению хп. Восстанавливает 10 хп. Стоит 3 аны";
здесь орфографическая ошибка - "аны"

2023-10-13 12:04 UTC, axtox commented on PizdilovoGame/GameLogic/ConsoleMessaging.cs
> +        public static void ShowMessage(string message,int _xCoordinate=0, int _yCoordinate=0 )
названия аргументов методов всегда с маленькой буквы, а с нижним подчеркиванием только приватные поля классов - private string _pole;

2023-10-13 12:04 UTC, axtox commented on PizdilovoGame/Program.cs
> +                ConsoleMessaging.ShowGameInfoCursor00($"Произошло что-то непредвиденное и программа дальше работать не будет. Смотрите логи в папке {Environment.SpecialFolder.ApplicationData}");
00 выглдяит неестесственно для C#,  лучше написать просто ShowGameInfo где будет подразумеваться что оно всегда одном месте

2023-10-13 12:08 UTC, axtox commented on PizdilovoGame/Buffs/HpRestoring.cs
> +        public string Description { get; } = "Заклинание по восстановлению хп. Восстанавливает 10 хп. Стоит 3 аны";
исправлено в  649f5a21762f9f90f2f7fcc16d6b6de2f4238d24

2023-10-13 12:08 UTC, axtox commented on PizdilovoGame/GameLogic/ConsoleMessaging.cs
> +        public static void ShowMessage(string message,int _xCoordinate=0, int _yCoordinate=0 )
исправлено 649f5a21762f9f90f2f7fcc16d6b6de2f4238d24

2023-10-13 12:08 UTC, axtox commented on PizdilovoGame/Program.cs
> +                ConsoleMessaging.ShowGameInfoCursor00($"Произошло что-то непредвиденное и программа дальше работать не будет. Смотрите логи в папке {Environment.SpecialFolder.ApplicationData}");
исправлнео 649f5a21762f9f90f2f7fcc16d6b6de2f4238d24

2024-04-03 18:50 UTC, axtox approved these changes
Исправил использования и перенес оставшиеся печати текста в наш класс, обновил мастер

2024-04-22 19:13 UTC, merged