Saving players by json serialized
Krechin94/FirstGame pull request #6
Opened 2023-03-30 19:30 UTC by Krechin94

Создание класса сохраняющего файлы

2023-04-23 14:56 UTC, axtox requested changes

2023-04-23 14:56 UTC, axtox commented on PizdilovoGame/GameLogic/SavingPlayers.cs
> +            player.HP = 10;
В сеттере свойства HP и Mana есть выбрасываение события "HpOrManaChanged` которые отработают вот тут и выполняться методы которые подписаны на это событие

Самое безобидное что тут произойдет это в консоль 6 раз напишется что кто-то выиграл в конце игры, а так же ХП сто раз обновится в информационном блоке справа

2023-04-23 14:56 UTC, axtox commented on PizdilovoGame/Program.cs
> +                {;
очень очень интересный баг - это абсолютно валидный код, поэтому ошибок при билде нет

тут можно попасть в очень серьезную проблему. Сейчас, в данном случае, эта одинокая `;` находится внутри блока кода, между скобок - `{` `}`, а значит будет распознано как пустая строка с ничем, и здесь ничего не произойдет

но если бы `;` стояла ПЕРЕД блоком, то компилятор бы распознал это как:
`if (currentChamp.HP > anotherChamp.HP);`
так как компилятору пофигу на пробелы и разрывы строк, он просто бы поставил эту `;` в конец if и тогда бы код в блоке между скобок - `{` `}` не выполнился бы. Потому что `;` означает конец выражения, стало быть он бы выполнил if и пошел бы дальше, не заходя внутрь фигурных скобок. И это тоже был бы валидный код, и ты бы очень долго не понимал почему условие не выполняется, а оно выполняется..

2023-04-23 14:56 UTC, axtox commented on PizdilovoGame/GameLogic/PlayerCreator.cs
> +        VvodChisla vvodChisla = new VvodChisla();
здесь следует указать тоже что это приватное поле как поле ниже, чтобы все было в одном стиле и именовать с `_`

2023-04-23 14:56 UTC, axtox commented on PizdilovoGame/GameLogic/PlayerCreator.cs
> +        private static string _pathToAppData = Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData);
следует добавить пробел после всех полей чтобы отделить визуально от методов

2023-04-23 14:56 UTC, axtox commented on PizdilovoGame/GameLogic/SavingPlayers.cs
> +        private static string _pathToAppData = Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData);
второй раз встречается `_pathToAppData` - ощущение что этот путь надо получать из какого-то менеджера, который занимается созданием игровой папки с сохранениями

2023-04-23 14:56 UTC, axtox commented on PizdilovoGame/Program.cs
> +                List<Player> listofPlayers = new List<Player>();
второй раз встречается список игроков, только этот лист, а `_players` это массив, следует оставить что-то одно (лучше лист)

2023-04-23 14:56 UTC, axtox commented on PizdilovoGame/Rassi/Elf.cs
> +            HP = 10;
это навсегда изменилась логика игры или это было для тестов? следует вернуть как было, если второй вариант

2023-04-24 12:41 UTC, Krechin94 commented on PizdilovoGame/Program.cs
> +                {;
[иправление количества хп у эльфов и убрал ненужную точку с запятой](https://github.com/Krechin94/FirstGame/pull/6/commits/278a948dcfadae0146513616ef1ff60c571cb974)

2023-04-24 12:41 UTC, Krechin94 commented on PizdilovoGame/Rassi/Elf.cs
> +            HP = 10;
[иправление количества хп у эльфов и убрал ненужную точку с запятой](https://github.com/Krechin94/FirstGame/pull/6/commits/278a948dcfadae0146513616ef1ff60c571cb974)

2023-04-24 12:56 UTC, Krechin94 commented on PizdilovoGame/GameLogic/SavingPlayers.cs
> +        private static string _pathToAppData = Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData);
[добавление переменной в класс работы с файлами, теперь она везде бере…](https://github.com/Krechin94/FirstGame/pull/6/commits/4f5e3402e189acd6a63fe62498d405ba4eed469c)

2023-04-27 14:59 UTC, Krechin94 commented on PizdilovoGame/GameLogic/PlayerCreator.cs
> +        VvodChisla vvodChisla = new VvodChisla();
[исправления с разметкой страницы и названиями переменных](https://github.com/Krechin94/FirstGame/pull/6/commits/3ca0cf921b54b65179329ef1ec468b6e4bf8bd0b)

2023-04-27 14:59 UTC, Krechin94 commented on PizdilovoGame/GameLogic/PlayerCreator.cs
> +        private static string _pathToAppData = Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData);
[исправления с разметкой страницы и названиями переменных](https://github.com/Krechin94/FirstGame/pull/6/commits/3ca0cf921b54b65179329ef1ec468b6e4bf8bd0b)

2023-04-27 15:01 UTC, Krechin94 commented on PizdilovoGame/Program.cs
> +                List<Player> listofPlayers = new List<Player>();
[удаление ненужного листа](https://github.com/Krechin94/FirstGame/pull/6/commits/d7bb9e3af9407e9f4cc42ba8c6da1a7ecb50b2b2)

2023-04-27 15:01 UTC, Krechin94 commented on PizdilovoGame/GameLogic/SavingPlayers.cs
> +            player.HP = 10;
[теперь хп меняются не при записи а при загрузке](https://github.com/Krechin94/FirstGame/pull/6/commits/3eb8590cea7aa9611e810310afb778e410c74760)

2023-05-06 23:16 UTC, axtox commented on PizdilovoGame/GameLogic/WorkWithFileLogic.cs
> +        public static string pathToAppData = Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData);
Здесб можно так же создать еще для сейвов игры свойство, а это свойство можно переписать прибавив `\PizdelovoGame` путь

2023-05-06 23:16 UTC, axtox commented on PizdilovoGame/GameLogic/SavingPlayers.cs
> +        private static string _pathToAppData = Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData);
Удалено в c533a499b4a09eb98d74b8d918356a7c22caffe1

2023-05-06 23:17 UTC, axtox requested changes

2023-05-06 23:17 UTC, axtox commented on PizdilovoGame/GameLogic/WorkWithFileLogic.cs
> +        public static string pathToAppData = Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData);
решено в c533a499b4a09eb98d74b8d918356a7c22caffe1

2023-05-06 23:17 UTC, axtox commented on PizdilovoGame/GameLogic/WorkWithFileLogic.cs
> +        public static string pathToAppData = Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData);
решено в c533a499b4a09eb98d74b8d918356a7c22caffe1

2023-05-06 23:19 UTC, axtox approved these changes

2023-05-06 23:20 UTC, merged